# Set up the prompt

setopt histignorealldups sharehistory

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Colors
autoload -U colors
colors
setopt prompt_subst

# Show completion on first TAB
setopt menucomplete

# Use modern completion system
autoload -Uz compinit
compinit

# ls alias to enable colors by default
alias ls="${aliases[ls]:-ls} --color=auto"
alias g="git"

# include vagrant user rubygems on PATH
PATH="/home/vagrant/bin:$PATH"
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# Prompt format
git_prompt_info() {
  git symbolic-ref --short HEAD
}

get_git_dirty() {
  git diff --quiet || echo '⚡'
}

autoload -Uz promptinit
setopt prompt_subst
promptinit

PROMPT='%K{blue}%n%k %B%F{green}%~ %B%F{cyan}($(git_prompt_info)%f) %F{yellow}$(get_git_dirty)%f $%b '
RPROMPT='%D{%H:%M:%S}'
